version: '3.9'

services:
  develop:
    build:
      context: ./sd-scripts/
      dockerfile: Dockerfile
    volumes:
      - ./sd-scripts:/app
      - ./data:/data
    command: bash /bin/bash
    tty: true
